spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123321
    url: jdbc:postgresql://localhost:5432/pp_diary
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret:
      expiry: 604800000 # 1 month
      key: c2Fsb21hbGlob25qb25iZWtha2FzaWxhcml5YXhzaGl5dXJpYnRpbWk=